name: build macOS App
on:
    push:
      branches:
        - main
      tags:
        - 'v*'

jobs:
    changelog:
        name: Generate Changelog
        runs-on: ubuntu-latest
        outputs:
          release_body: ${{ steps.git-cliff.outputs.content }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Generate a changelog
            uses: orhun/git-cliff-action@v2
            id: git-cliff
            with:
              config: git-cliff/cliff.toml
              args: -vv --latest --strip 'footer'
            env:
              OUTPUT: CHANGES.md
          - name: Release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
              body: ${{ steps.git-cliff.outputs.content }}
              token: ${{ secrets.GITHUB_TOKEN }}
            env:
              GITHUB_REPOSITORY: ${{ github.repository }}

    build:
      runs-on: macos-13
      outputs:
        release_body: ${{ steps.git-cliff.outputs.content }}
  
      steps:
      - uses: actions/checkout@v4
  
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '15.0.1'
      
      - name: Install the Apple certificate and provisioning profile
        env:
              BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
              P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
              KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
            # create variables
            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
    
            # import certificate and provisioning profile from secrets
            echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
    
            # create temporary keychain
            security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
    
            # import certificate to keychain
            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build the App
        run: xcodebuild -project GitHubSwiftBar.xcodeproj -scheme GitHubSwiftBar -configuration Release -derivedDataPath build  

      - name: Install create-dmg
        run: brew install create-dmg
    
      - name: Create DMG
        run: create-dmg "GitHubSwiftBar.dmg" 'build/Build/Products/Release/'
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: GitHubSwiftBar.dmg
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

          
  
