name: build macOS App
on:
    push:
      branches:
        - main

jobs:
    build:
      runs-on: macos-13
  
      steps:
      - uses: actions/checkout@v4
  
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '15.0.1'
  
      - name: Build the App
        run: xcodebuild -project GitHubSwiftBar.xcodeproj -scheme GitHubSwiftBar -configuration Release -derivedDataPath build  

          
  
